# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vite-store-ext"
client_id = "b592f6b30431fac8d607f05d8c76bb1c"
application_url = "https://subsequent-antonio-discipline-contests.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://subsequent-antonio-discipline-contests.trycloudflare.com/auth/callback",
  "https://subsequent-antonio-discipline-contests.trycloudflare.com/auth/shopify/callback",
  "https://subsequent-antonio-discipline-contests.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellostorexyz.myshopify.com"
